---
- name: Deploy Kubernetes resources using manifest file
  hosts: qa
  become: true
  tasks:
    - name: Check if Deployment exists
      community.kubernetes.k8s_info:
        api_version: apps/v1
        kind: Deployment
        namespace: default
        name: abc-pod
      register: existing_deployment
      ignore_errors: yes

    - name: Delete Deployment if exists
      community.kubernetes.k8s:
        state: absent
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: abc-pod
            namespace: default
      when: existing_deployment.exists

    - name: Check if Service exists
      community.kubernetes.k8s_info:
        api_version: v1
        kind: Service
        namespace: default
        name: abc-svc
      register: existing_service
      ignore_errors: yes

    - name: Delete Service if exists
      community.kubernetes.k8s:
        state: absent
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: abc-svc
            namespace: default
      when: existing_service.exists

    - name: Apply manifest file using kubectl
      command: kubectl apply -f 
      args:
        executable: /bin/bash
